# Generated by Django 4.0.4 on 2022-10-03 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('8ff7b18a-ba73-48db-8d9b-0cc092fde385'), editable=False, max_length=30),
        ),
    ]
