# Generated by Django 4.0.4 on 2022-10-03 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('7db7efbe-ac90-4175-b458-22d0a2433486'), editable=False, max_length=30),
        ),
    ]
