# Generated by Django 4.0.4 on 2022-10-03 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('abcf02cb-95af-467f-9e02-c8e51e7c472f'), editable=False, max_length=30),
        ),
    ]
