# Generated by Django 4.0.4 on 2022-10-10 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('6f54ee01-849a-451a-8f37-b9f56c98f94e'), editable=False, max_length=30),
        ),
    ]
