# Generated by Django 4.0.4 on 2022-10-10 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('f7117ce1-44b4-4308-8e70-2fb8b71efe5f'), editable=False, max_length=30),
        ),
    ]
