# Generated by Django 4.0.4 on 2022-10-10 06:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('69289a01-6b88-4069-b360-6a11b2230e3b'), editable=False, max_length=30),
        ),
    ]
