# Generated by Django 4.1.1 on 2022-10-13 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('035e0582-3e68-42d5-9b3a-26c19afd22bc'), editable=False, max_length=30),
        ),
    ]
