# Generated by Django 4.1.1 on 2022-10-13 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('01547dce-a8e3-4837-bff3-83e30f18a0f1'), editable=False, max_length=30),
        ),
    ]
