# Generated by Django 4.1.1 on 2022-10-13 12:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('897f4b95-f9be-4ebf-8ffc-615495192214'), editable=False, max_length=30),
        ),
    ]
