# Generated by Django 4.1.1 on 2022-10-13 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('af3507e4-27be-4c18-8c3b-5c3f9bed5095'), editable=False, max_length=30),
        ),
    ]
