# Generated by Django 4.1.1 on 2022-10-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='myshopweb/images/products')),
                ('size', models.CharField(default='', max_length=6)),
                ('material', models.CharField(default='', max_length=20)),
                ('sleeve_length', models.CharField(default='', max_length=20)),
                ('season', models.CharField(default='', max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='Category')),
                ('manufacturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer', verbose_name='Manufacturer')),
            ],
        ),
    ]
