# Generated by Django 4.1.1 on 2022-09-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_alter_product_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
