# Generated by Django 4.0.4 on 2022-10-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_material_product_season_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='../images/products'),
        ),
    ]
