# Generated by Django 4.0.4 on 2022-09-14 03:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('3d8f24fc-431f-416a-a456-a78eecf8ee3c'), editable=False, max_length=30),
        ),
    ]
