# Generated by Django 4.0.4 on 2022-09-14 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('495b9dab-9b87-46ff-a1a5-a1457b3f3462'), editable=False, max_length=30),
        ),
    ]
