# Generated by Django 4.0.4 on 2022-09-14 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('21aad3c2-8844-4781-abb2-48caaa2c0c0c'), editable=False, max_length=30),
        ),
    ]
