# Generated by Django 4.1.1 on 2022-10-09 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.CharField(blank=True, default=uuid.UUID('c86e7f56-e0de-4c0d-a3cc-7efd382f2b17'), editable=False, max_length=30),
        ),
    ]
