# Generated by Django 4.1.1 on 2022-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('subject_name', models.CharField(max_length=30)),
                ('contents', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
