# Generated by Django 4.0.4 on 2022-09-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
